### ISSUE TITLE
Prepare for upcoming Seurat v5 release

### ISSUE THREAD

**Issue by Gesmira** [jianhong/scRNAseqApp#1]
I am opening this issue as a notification because `scRNAseqApp` is listed [here](https://cran.r-project.org/web/packages/Seurat/index.html) as a package that relies (depends/imports/suggests) on Seurat. As you may know, we recently released Seurat v5 as a beta in March of this year, with new updates for spatial, multimodal, and massively scalable analysis. For more information on updates and improvements, check out our website https://satijalab.org/seurat/.
We are now preparing to release Seurat v5 to CRAN, and plan to submit it on October 23rd. While we have tried our best to keep things backward-compatible, it is possible that updates to Seurat and SeuratObject might break your existing functionality or tests. We wanted to reach out before the new version is on CRAN, so that there's time to report issues/incompatibilities and prepare you for any changes in your code base that might be necessary.

We apologize for any disruption or inconvenience, but hope that the improvements to Seurat v5 will benefit your users going forward.
To test the upcoming release, you can install Seurat from the `seurat5` branch using the instructions available on this page: https://satijalab.org/seurat/articles/install.

Thank you!
Seurat v5 team

**Comment by tuhulab** [comment]
Update again: `JoinLayers` should be performed before generating data for the App :-)
Update: scRNAseqApp (`1.3.13`) Seurat (`5.0.2`) gives the same error

I have experienced a disruption after upgrading to Seurat v5.

When I have multiple layers, there's an error: `**! GetAssayData doesn't work for multiple layers in v5 assay**`. Any advice on a quick fix?

scRNAseqApp (`1.2.2`) Seurat (`5.0.1`)

**Comment by jianhong** [comment]
Did you tried to JoinLayers before generate the App data? Let me know if it does not work or it is not what you want.

**Comment by tuhulab** [comment]
> Did you tried to JoinLayers before generate the App data? Let me know if it does not work or it is not what you want.

Thx, @jianhong. It works after `JoinLayers`.
