### ISSUE TITLE
How to create abstract for the dataset?

### ISSUE THREAD

**Issue by tuhulab** [jianhong/scRNAseqApp#2]
Hi @jianhong, how can I create abstract for the dataset?

![image](https://github.com/jianhong/scRNAseqApp/assets/45359616/38ccad03-1f92-4ecb-8a52-93be3ab9041e)

**Comment by jianhong** [comment]
I should write this in the documentation. 

Do it like this:
```
appconf <- createAppConfig(
title="pbmc_small",
destinationFolder = "pbmc_small",
species = "Homo sapiens",
doi="10.1038/nbt.3192",
datatype = "scRNAseq")

appconf$ref$entry$abstract <- 'abstract here'
```

Previously, the abstract will be retrieved automatically, but this does not happy anymore.

**Comment by jianhong** [comment]
I updated the development version with abstract parameter for createAppConfig. Hope this will help.
